
# pluginを削除するコマンド
# :call dein#recache_runtimepath()

[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

[[plugins]]
repo  = 'cespare/vim-toml'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
#repo = 'scrooloose/nerdtree'

#[[plugins]]
#repo = 'Xuyuanp/nerdtree-git-plugin'

#[[plugins]]
#repo = 'jistr/vim-nerdtree-tabs'

#[[plugins]]
#repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'sheerun/vim-polyglot'

